### ISSUE TITLE
Cost assignment in Multi Agent Intersection Environment

### ISSUE THREAD

**Issue by dineshresearch** [metadriverse/metadrive#150]
My understanding is that xxx_cost is used only for evaluation (calculation of crash vehicle rate, crash object rate, out of road rate).
If it is correct, it seems strange for me that the cost values are not 1.0. 

In marl_intersection.py

def _long_run():
    # Please refer to test_ma_Intersection_reward_done_alignment()
    _out_of_road_penalty = 3
    env = MultiAgentIntersectionEnv(
        {
            "num_agents": 32,
            "vehicle_config": {
                "lidar": {
                    "num_others": 8
                }
            },
            **dict(
                out_of_road_penalty=_out_of_road_penalty,
                crash_vehicle_penalty=1.333,
                crash_object_penalty=11,
           

>      crash_vehicle_cost=13,

                crash_object_cost=17,
                out_of_road_cost=19,
            )
        }
    )

Can you please clarify @QuanyiLi @pengzhenghao

**Comment by pengzhenghao** [comment]
The cost is return to the user via the info dict given by the env.step

If they are all 1, then the average:

np.mean([i[“xx_cost”] for i in infos])

Is the xx_rate as you said.

But we can easily change the scale of those penalty and let them as arbitrary values. This is helpful as it is the cost function engineering useful in many safe RL algorithm.

Also, the code you shown here is for test only.

Hope the helps!
