### ISSUE TITLE
Trying to add (1280, 720) camera to single agent

### ISSUE THREAD

**Issue by bbenja** [metadriverse/metadrive#152]
I tried adding (1280, 720) camera to a single agent so i could record images for a dataset, but when i save the image its the default size (84, 84). Changing `env.enigne.global_config` and/or `env.config` both does nothing. I've used:

```
config = dict(environment_num=100,
              use_render=True,
              manual_control=True,
              traffic_density=0.1,
              show_logo=False,
              map=7,
              start_seed=20,
              offscreen_render=True,
              cull_scene=True,
              rgb_clip=False,
              window_size=(1280, 720),
              # vehicle_config=dict(rgb_camera=(1280, 720))
              )

env = metadrive.MetaDriveEnv(config)
o = env.reset()

env.engine.global_config.update({"target_vehicle_configs": {"default_agent":
                                                                dict(rgb_camera=(1280, 720),
                                                                     image_source="rgb_camera")}})
env.config.update({"target_vehicle_configs": {"default_agent":
                                                  dict(rgb_camera=(1280, 720),
                                                       image_source="rgb_camera")}})

cam = env.vehicles["default_agent"].image_sensors["rgb_camera"]
```

I had some success with adding `vehicle_config=dict(rgb_camera=(1280, 720))` to the initial config, before making the environment, but that drops fps significantly (to 2-3 FPS).

**Comment by QuanyiLi** [comment]
Hi bbenja,

Sorry for the late reply. 

You can find a script at: [metadrive/tests/vis_functionality/vis_rgb_cam.py](https://github.com/decisionforce/metadrive/blob/main/metadrive/tests/vis_functionality/vis_rgb_cam.py), which renders and saves the images captured by RGB camera in an offline and efficient manner. 

Simply modify the env_config to:
```
env = MetaDriveEnv(
        {
            "environment_num": 1,
            "traffic_density": 0.1,
            "start_seed": 4,
            "manual_control": True,
            "use_render": False,
            "offscreen_render": True,  # it is a switch telling metadrive to use rgb as observation
            "rgb_clip": True,  # clip rgb to range(0,1) instead of (0, 255)
            "vehicle_config": {"image_source":"rgb_camera", "rgb_camera":(1280, 720)}
        }
    )
```
Then you can get 1280*720 first-view images.

Quanyi

**Comment by QuanyiLi** [comment]
Also, the first-view images rendered in ```use_render: True``` mode (with window) and  ```use_render: False``` mode (without window) **may** be **different**. As far as I know, first view images which are offscreen rendered on Windows11 may draw mesh of the models, while images rendered in onscreen mode do not.

So please check images rendered in both modes to figure out if the offscreen rendered images satisfy your requirements. If the offscreen rendered images are in a bad quality, i.e. containing mesh, you have to do onscreen render, which is much slower than offscreen render.

**Comment by baheytharwat** [comment]
@QuanyiLi Is it possible to change the location and fov of a camera? If yes, how? and can I add more than one camera?

**Comment by pengzhenghao** [comment]
You can adjust the main camera by changing the config:

```
config["camera_height"]=1.8 
config["camera_dist"]=6.0  # Distance to the ego car
```

I think you can add more camera, but need to modify the source code similar to how we define and use `engine.main_camera`

<img width="562" alt="image" src="https://user-images.githubusercontent.com/22206995/218381169-616daa7b-614a-45ec-bb94-d8ed6daef2ae.png">

**Comment by QuanyiLi** [comment]
Hi @baheytharwat 
Do you mean the camera capturing the third-person view interface? Or add a camera to the vehicle so it can capture more figures? 

If you mean the former one, you can get lens for each env by ```main_cam=env.engine.main_camera.camera.node().getLens()```. Then, you can adjust the Fov by ```main_cam.setFov(60)```. For changing other attribute, you can refer to: https://docs.panda3d.org/1.10/python/programming/camera-control/perspective-lenses and https://docs.panda3d.org/1.10/python/reference/panda3d.core.Lens#panda3d.core.Lens.setFov

If you mean the latter one. You can use ```add_image_sensor("name", sensor)``` for each vehicle to add new camera, like ```env.vehicle.add_image_sensor("rgb_cam_2", RGBCamera())```. After adding new sensor, you can also change the lens properties of this sensor, for example:
```
lens=env.vehicle.image_sensor["rgb_cam_2"].get_lens() 
lens.setFov(target_value)
```

Feel free to ask questions, if there are still something unclear : )

Quanyi
