### ISSUE TITLE
waypoints for generalization and safe metadrive environment

### ISSUE THREAD

**Issue by jayabrata97** [metadriverse/metadrive#183]
@QuanyiLi and @pengzhenghao, Is there any way to get the location of way points to follow during driving? Currently environment reward uses these way points to calculate reward internally. Is there any way to get vehicle position and way point positions? Also it will be helpful if you can direct me to the scripts where those are defined. Thanks in advance.

**Comment by QuanyiLi** [comment]
Hi, 

We do not have the concept of waypoints. Instead, we have ```vehicle.navigation.current_ref_lane```,  a continuous lane line, which indicates the driving direction of current position, so if you need waypoints, you can sample them from this reference lane. 

With the ```vehicle.navigation.current_ref_lane```, the basic driving reward is calculated by the moving distance on the reference lane under the frenet coordinates, as shown in https://github.com/metadriverse/metadrive/blob/6ea101a0d8da1fe825828f32f672e22af00746da/metadrive/envs/metadrive_env.py#L218 For the complete reward function definition, please refer to our paper: https://arxiv.org/pdf/2109.12674.pdf

Besides, the vehicle position could be accessed by ```vehielce.position```.  Other all properties of vehicles could be found in https://github.com/metadriverse/metadrive/blob/6ea101a0d8da1fe825828f32f672e22af00746da/metadrive/component/vehicle/base_vehicle.py#L37 

Quanyi
