### ISSUE TITLE
[Bug] env close bug when reset env more than once

### ISSUE THREAD

**Issue by PaParaZz1** [metadriverse/metadrive#191]
Hi, I found a tiny bug when call metadrive env like following code:
```python
env = BaseEnv(BaseEnv.default_config())
env.reset()
env.close()
env.reset()  # bug point
```
In a process, after calling `close` method, `self.engine` is not set to None, so when I call `reset` method twice, it will trigger [this ValueError](https://github.com/metadriverse/metadrive/blob/main/metadrive/envs/base_env.py#L329), can you fix it in future update?

**Comment by pengzhenghao** [comment]
This is indeed a bug. A early stage of MetaDrive support close and re-reset, but now this feature is broken.

@QuanyiLi Do you think this issue is solvable? If so, we can schedule the fix in next week
