### ISSUE TITLE
About the fantastic picture in the paper.

### ISSUE THREAD

**Issue by xjtueryx** [metadriverse/metadrive#193]
I saw very nice pictures in the paper, how do you draw these colored trajectories? Does metadrive open source this simple visualization environment? Looking forward to your reply.

**Comment by QuanyiLi** [comment]
Yes, it is the built-in&nbsp;topdown renderer. Use env.render(mode=“topdown”) to launch it. It is mostly used in the MARL environment and you can learn about the usage of this renderer in the MARL example, shown in README.md.






------------------ Original ------------------
From: xjtueryx ***@***.***&gt;
Date: Tue, Jun 28, 2022 1:09 AM
To: metadriverse/metadrive ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [metadriverse/metadrive] About the fantastic picture in the paper.(Issue #193)





 
I saw very nice pictures in the paper, how do you draw these colored trajectories? Does metadrive open source this simple visualization environment? Looking forward to your reply.
