### ISSUE TITLE
During training any option or Flag to visualize metadrive screen   

### ISSUE THREAD

**Issue by dineshresearch** [metadriverse/metadrive#201]
I want to view the metadrive screen during the training. So that i can check how the vehicles are behaving on the road during training process

**Comment by pengzhenghao** [comment]
Our way is to download the checkpoint from server (the machine that you use to train RL) and use specific script to restore the weights from checkpoint and build a policy in local machine and then run environment with visualization enabled. And the process to visualize things are completely detached from the machine / program / code for training, which is a good practice for RL practitioners.

As an example, here is the script to load model and run environment:

https://github.com/decisionforce/CoPO/blob/main/copo_code/copo/vis_from_checkpoint.py

We have two ways to enable visualization:

First, use native Panda3D renderer (which usually causes errors in remote server). You can set config with flat `use_render`: `EnvClass({"use_render": True})` and then a window should pop up.

Third, use pygame renderer. (I think this is a good way for you if you want to visualize things during training). You don't need to set any config. Just call `env.render(mode="topdown")` at each step of RL loop, as:

https://github.com/decisionforce/CoPO/blob/main/copo_code/copo/vis_from_checkpoint.py#L126

and this is it!
