### ISSUE TITLE
Multi-agent Parking Lot still has the "empty slot" issue in intensive experiment

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#212]
Here is where error happens:

![image](https://user-images.githubusercontent.com/22206995/193890392-7bcfa0a3-f0b2-4429-a033-d9ad11bfeb1c.png)

This situation becomes much rare than some version before, where MARL envs have many problems. Nevertheless, this issue still exists!

**Comment by QuanyiLi** [comment]
When developing the Colab script, I also encounter this problem.

Could you provide a script to reproduce this problem?

**Comment by pengzhenghao** [comment]
It's obviously a very probabilisitic issue. I will take a look on this but I guess the final solution is add some fallback mechanism.
