### ISSUE TITLE
Some error in run 'python -m metadrive.examples.drive_in_single_agent_env'

### ISSUE THREAD

**Issue by betray12138** [metadriverse/metadrive#268]
I follow the instruction and install the metadrive onto my machine with Linux Platform. However when I run the 'python -m metadrive.examples.drive_in_single_agent_env' command, I find the GUI interface will exit. After I change the code like the following:
![1](https://user-images.githubusercontent.com/55013174/210319687-c2a0476d-5a73-4919-99a1-b5c1cfbcf5cb.png)
and run this command again, the exceptions I met  are as following:
![2](https://user-images.githubusercontent.com/55013174/210319783-44482644-4fbd-4fde-9b82-c809618476ce.png)
So how could I do to solve this problem ?

**Comment by pengzhenghao** [comment]
Thanks for reporting! I will check it today.
