### ISSUE TITLE
Would maintaining self.engine = engine cause circular reference?

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#280]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/22206995/217727027-e00aa41d-60b9-4642-8d03-b543689bf775.png">

Maybe we should allow each class to have a property:

```
@property
def engine(self):
    return get_engine()
```

**Comment by QuanyiLi** [comment]
If use:
```
@property
def engine(self):
    return get_engine()
```
won't cause a lot of latency, then go ahead. My main concern about this way is that getting the engine every time you need it will cost a huge amount of time.
