### ISSUE TITLE
Add dependencies of Nuplan to setup.py

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#283]
Like hydra and nuplan.

Also update README and docs on how to install these dependencies.

**Comment by QuanyiLi** [comment]
Should we provide different installation options for users? NuPlan has too many dependencies and requires Python3.9. I remember that you can install a lib like ```pip install metadrive[nuplan]```. Do you know how to do this?

**Comment by pengzhenghao** [comment]
I know. That’s what I expectBest,ZhenghaoOn Feb 10, 2023, at 15:02, Quanyi Li ***@***.***> wrote:﻿
Should we provide different installation options for users? NuPlan has too many dependencies and requires Python3.9. I remember that you can install a lib like pip install metadrive[nuplan]. Do you know how to do this?
