### ISSUE TITLE
Access rendered image on GPU via Torch

### ISSUE THREAD

**Issue by QuanyiLi** [metadriverse/metadrive#306]
I learned that it is feasible to accelerate camera efficiency by accessing the rendered image on GPU without moving to RAM:

**Reference:**
1. https://discourse.panda3d.org/t/allowing-torch-tensorflow-to-directly-access-rendered-image-in-gpu/29119/2
2. https://discourse.panda3d.org/t/how-to-get-gpu-memory-pointer-from-texture-object/27983/3
3. #290 
4. https://www.3dgep.com/opengl-interoperability-with-cuda/
5. https://discuss.pytorch.org/t/transfer-cuda-memory-to-libtorch-tensor/144827/2
6. Torch::from_blob: https://discuss.pytorch.org/t/opengl-libtorch-and-cuda-interop-doing-inference-on-texture-data/165926
7. CuPy and CUDA-Python: https://gist.github.com/keckj/e37d312128eac8c5fca790ce1e7fc437

I would like to try this, as visuomotor policy training is one drawback for MetaDrive.

**Comment by QuanyiLi** [comment]
I make it!

Running: ```/home/shady/data/metadrive/metadrive/tests/vis_functionality/vis_cuda_image.py```

FPS Before optimization: 1100~
FPS After optimization: **4000+**

**Comment by QuanyiLi** [comment]
@jon-chuang 
Would you like to accelerate image retrieval? I just tested a new feature that supports accessing the rendered image without copying it to the host memory. All things happen on GPU now!

**Comment by QuanyiLi** [comment]
## New test results in MetaDrive Env

Script: ```metadrive/tests/vis_functionality/vis_profile_metadrive_cuda.py```

Setting: 
- 3 block
-  no traffic
-  agent policy: IDM policy
- Image size: 1920 * 1080

Result:
Ram Image (old): 25 FPS
CUDA Image (new): **385 FPS** 

Amazing!

**Comment by pengzhenghao** [comment]
Can only run `vis_cuda_make_buffer.py` with this:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/22206995/221514555-0ba846a0-c299-433b-aef9-0381f1b06a97.png">

All other `vis_cuda` fail with:

<img width="1619" alt="image" src="https://user-images.githubusercontent.com/22206995/221514691-faf42a4e-d020-452d-a4a6-cb8dc2da9c56.png">

Might caused by wrongly installed cupy in Windows. I can't install it through `pip install cupy-cuda12x` and can only install via `conda install -c conda-forge cupy`

**Comment by QuanyiLi** [comment]
I have already 
1. Fixed this problem on windows
2. Added installation instructions to Doc. 

Please check the Installation section, follow the guide and help me verify the installation pipeline and check my writing.

**Comment by jon-chuang** [comment]
Amazing! Thanks for working on this.

Unfortunately, we require the image buffer to be in memory. Furthermore, the target we'd like to optimize most for is CPU-only setups.

**Comment by mimi89999** [comment]
Hello,
Would it be possible to do the same thing with OpenCL?

**Comment by QuanyiLi** [comment]
@mimi89999 I think so. Just search the keyword: OpenGL OpenCL interop python. There are many discussions like this: https://cyrille.rossant.net/a-tutorial-on-openglopencl-interoperability-in-python/#:~:text=With%20OpenCL%2DOpenGL%20interoperability%2C%20one,GPU%20memory%20at%20all%20times.

But for OpenCL to Torch, I am not sure if there is some tools helping with it. (Though I know torch has OpenCL backend)
