### ISSUE TITLE
can you upgrade gym version to 0.25.1

### ISSUE THREAD

**Issue by PaParaZz1** [metadriverse/metadrive#307]
I find metadrive only supports `"gym>=0.20.0, <=0.22.0"`, can you do some compatibility test and upgrade the highest version to 0.25.1?

**Comment by QuanyiLi** [comment]
@pengzhenghao I found that the main update of ```gym-0.25.1``` is the return value of ```env.step``` and ```env.reset```, right? In this case, we can provide a wrapper for making MetaDrive compatible with it.

**Comment by pengzhenghao** [comment]
I'll follow up this request
