### ISSUE TITLE
Visualize the problem after ray training

### ISSUE THREAD

**Issue by shile1998** [metadriverse/metadrive#315]
After EGPO training, I want to display the environment in metadrive, can you provide the corresponding code, I am not familiar with ray

**Comment by shile1998** [comment]
Visualization of the most basic SAC algorithm

**Comment by pengzhenghao** [comment]
Thanks for reaching

A basic logic is:

1. Instantiate the "Trainer" instance from RLLib with proper config.
2. Restore checkpoint
3. Create environment
4. Rollout the environment and probably render / record the visualization.

```python

# Create and restore your agent
from ray.rllib.agents.sac import SACTrainer
...

trainer = SACTrainer({some config identical to your training config})
trainer.restore(CHECKPOINT_FOLDER_PATH)

...

# Create environment
env = SafeMetaDrive({some env config})
...


# Rollout
action = trainer.compute_single_action(obs)
o, r, d, i = env.step(action)

...
```
