### ISSUE TITLE
display(warning): FrameBufferProperties available less than requested.

### ISSUE THREAD

**Issue by GeYuhong** [metadriverse/metadrive#329]
After upgrading the system from 16.04 to 20.04, the rendered image is very sluggish and completely unusable. When running the program, the following prompt appears:
:display(warning): FrameBufferProperties available less than requested.
  requested: depth_bits=1 color_bits=3 red_bits=1 green_bits=1 blue_bits=1 alpha_bits=1 multisamples=8 back_buffers=1 force_hardware 
  got: depth_bits=32 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 multisamples=4 back_buffers=1 force_hardware force_software

How can I solve this problem, thx

**Comment by QuanyiLi** [comment]
Hi,

What do you mean by *sluggish*? Is that a low rendering FPS when visualizing with the 3D renderer? If so, I suspect that the program doesn't run on your GPU. You can check this by ```nivida-smi``` when running your program. Besides, could you give me more information, like:

1. Ubuntu or WSL2
2. GPU 
3. CPU
4. MetaDrive version
5. Panda3d version
