### ISSUE TITLE
Do metadrive support multi agent RL algorithms particularly MAPPO? Did any one tested?

### ISSUE THREAD

**Issue by Mming11** [metadriverse/metadrive#333]
Since lightweight version of MAPPO can quickly migrate to local environment, I want to ask if anyone test.

**Comment by pengzhenghao** [comment]
Our CoPO repo provides PPO baseline.https://github.com/decisionforce/CoPOBest,ZhenghaoOn Mar 14, 2023, at 01:37, Mming11 ***@***.***> wrote:﻿
Since lightweight version of MAPPO can quickly migrate to local environment, I want to ask if anyone test.
