### ISSUE TITLE
AttributeError: module 'gltf' has no attribute 'patch_loader'

### ISSUE THREAD

**Issue by gulegeji** [metadriverse/metadrive#358]
WHEN RUN 
python -m metadrive.examples.drive_in_single_agent_env, THIS ERROR HAPPENS

MY ENVIRONMENT:
PYTHON 3.9.7
UBUNTU 20.04.6

**Comment by QuanyiLi** [comment]
Hi,

Thank you for the feedback. For fixing this, just downgrade ```gltf``` via ```pip install panda3d-gltf==0.13```. I already specify its version in latest main branch. Thanks for the feedback!
