### ISSUE TITLE
Asset lost after env.close() then creating new env

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#373]
![Screenshot from 2023-03-26 20-47-31](https://user-images.githubusercontent.com/22206995/227836248-9403280c-0cce-4095-944f-ec39d15679aa.png)

Run `test_export_metadrive_scenario(render_export_env=True, render_load_env=True)` in `test_export_scene.py`, you will see the second environment fails to render road structure.

**Comment by QuanyiLi** [comment]
Good to know. I will fix this

**Comment by QuanyiLi** [comment]
It is due to ```del env```. Already remove all del env

**Comment by QuanyiLi** [comment]
I think ```del env``` may clean some environment variables related to ```s_rgb color format```, which is required to correct road surface color.
