### ISSUE TITLE
Known issue: in test_export_scene.py, the replay scenario are horizontally flipped.

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#374]
Need to create a new PR to fix this.

**Comment by QuanyiLi** [comment]
As the WaymoEnv is right-hand coordinate, exported cases are in metadrive coordinate, which is left-hand. We don't have to fix it at this time, but just using WaymoEnv to test if cases can be exported and loaded. When I make the MetaDriveScenarioEnv, I will do this.

**Comment by pengzhenghao** [comment]
We fixed it!!!!
