### ISSUE TITLE
Discussion: Object Type formalization

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#380]
TODO:

* [ ] Check Nuplan object name
* [ ] Check any other place of string name that should be merged into MetaDriveType 

---

This is little discussion on the design choice. I saw we are using this to register different agent type. We also have another kind of objects in the environment, like Traffic Cone, Traffic Light and so on.

Here are my questions:

1. Should we stick to STRING to describe all objects instead of using Int?
2. Should we introduce a large "ObjectTypeClass" to make all objects within one class?

![Screenshot from 2023-03-27 11-39-01](https://user-images.githubusercontent.com/22206995/228036034-8649f389-e157-483b-acef-14fce896de11.png)

**Comment by pengzhenghao** [comment]
Also, this class falls into "Waymo Type". We should upgrade it to a global things, like put it in MetaDrive.constants

**Comment by pengzhenghao** [comment]
metadrive.constants defines some. But this is clearly mismatched from Waymo type names

![Screenshot from 2023-03-27 11-45-43](https://user-images.githubusercontent.com/22206995/228037240-303d2912-9ab0-4f40-9911-c5870c6e63f4.png)

**Comment by QuanyiLi** [comment]
1. yes
2. what do you mean by **all**, you mean objects related to scenarios exportation? or all metadrive object. If it is the former one, you can **not** merge them. As in waymo original format, number is used to represent type, 1 might be vehicle for AgentType but yellow_line for LineType.

**Comment by pengzhenghao** [comment]
@QuanyiLi Here is what I am thinking:

First, I am talking about all places. We should use a predefined set of strings to discribe all object types. And we will have a class to register this:

Option 1: A big class to store all types:

```python
# In metadrive.constants
class ObjectType:
    VEHICLE = "VEHICLE"
    TRAFFICLIGHT = "TRAFFICLIGHT"
    YELLOW_SOLID_LANE = "YELLOW_SOLID_LANE"
```


Option 2: Still using current method, but never use int in our code. It is OK to have a mapping function to transform from real dataset:
```python
# In metadrive.constants
class AgentType:
    VEHICLE = "VEHICLE"
    CYCLIST = "CYCLIST"

    @classmethod
    def from_waymo(waymo_agent_type: int):
        return {1: self.VEHICLE, 2: self.CYCLIST}
```


Second, when exporting data in the data format, still using the same string to describe the objects and never use any interger.
