### ISSUE TITLE
Sometimes atan2 sometimes -atan2

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#387]
What is the principle between this?

from abs_lane.py:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/22206995/228431618-a16c7ebf-991a-43af-87d0-b0695818c98c.png">

**Comment by QuanyiLi** [comment]
have no idea. At least it has nothing to do with the bug you encountered. I guess it is related to converting to panda coordinates

**Comment by QuanyiLi** [comment]
The following function uses it for setting a panda heading without times a ```-```. I am 99% sure it is an implicit heading convert. I already fixed it by calling explicit converting API.

**Comment by QuanyiLi** [comment]
I ran all tests, and find new failures caused by 
1. ```ReplayEgoCarPolicy```:  
action = self.traj_info[int(self.timestep)].get("action", None)
E       IndexError: list index out of range

2. ```def replay_frame()```:
for name, config in self.current_frame.spawn_info.items():
E       AttributeError: 'list' object has no attribute 'spawn_info'

**Comment by pengzhenghao** [comment]
This issue is resolved by introducing a general "panda_heading" function to transform heading angle.
