### ISSUE TITLE
Discussion: Rules to filter out unwanted scenarios in real-world dataset

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#390]
* Rule 1: Filter out if the total distance of moving of the ego vehicle < 10m

* Rule 2: Filter out if the total time when the ego vehicle is valid < 5s = 50 steps

**Comment by pengzhenghao** [comment]
First, whether it is necessary to do the rule 1&2? They are useful when creating the single-agent RL env. But what about MARL env and perception task? These tasks do not hold such constraint on the data!

Second, what about the case where the behavior of ego is not idea? 

1. the vehicle ends by "on_yellow_continuous_line" or "on_white_continuous_line". While it is possible to do so in real-world, in RL task this will raise out_of_road!!! (this is probably the reason why MAIRL sometimes fail)
2. the vehicle is not valid in the beginning but valid later during the 200step episode. 
3. the ego vehicle has some time step not valid, but later it recover. (I don't see this case for ego car, but occasionally see in traffic car)

**Comment by QuanyiLi** [comment]
1. We have enough cases. So just filter them to get a batch of high-quality cases. I believe that MARL env needs fewer data than single RL env, so why we don't use good data for MARL?

2. I changed the done condition to on_yellow_line or on_side_walk after upgrading sidewalk construction. I understand your concern that terminating when the vehicle is on the white line is not reasonable and is too restrict. 

3. We should have a discuss on the valid problem.
