### ISSUE TITLE
Add coordinate transform in Waymo converter 1 so the output SD is always MD coordinate

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#394]

**Comment by QuanyiLi** [comment]
Good proposal.

**Comment by pengzhenghao** [comment]
The most important issue here is the compatibility. We have to assess how many places people are still using the old data format. Best,ZhenghaoOn Mar 31, 2023, at 02:37, Quanyi Li ***@***.***> wrote:﻿
Good proposal.

**Comment by pengzhenghao** [comment]
I don't think this is necessary if we allow coordinate transform and record this information in SD.
