### ISSUE TITLE
Broken skybox

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#407]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/22206995/229941105-c238b6b5-d6d8-4a5d-82a8-36b59c5026c8.png">

Always happen at the first episode when running `scenario_env.py`.

**Comment by QuanyiLi** [comment]
Already fix in my the new PR. In some scenarios, the map center is far away from (0,0) and reaches the boundary of terrain and skybox. I reset the positions of terrain and skybox to the map center and fix it.
