### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AHPUymhd** [metadriverse/metadrive#428]
![图片](https://user-images.githubusercontent.com/72792297/233847591-35c63bc8-7287-42aa-91af-14b19c70630f.png)
![图片](https://user-images.githubusercontent.com/72792297/233847602-483cb429-77f4-4df2-ad0d-b520f1fafda3.png)
why!!!

**Comment by QuanyiLi** [comment]
Could you give me more information about your setting? Like how do you initialize your environment? I did some simple tests on the latest MetaDrive, but can not reproduce it.

**Comment by AHPUymhd** [comment]
initialize  environment is metadrive.envs.metadrive_env.py and I use MetaDrive-0.3.0.1 version  ,it maybe a problem of my conda?

**Comment by QuanyiLi** [comment]
Sorry, I can't reproduce your problem. It seems that the bug is not on our side. I tested with the following lines of code.
![Screenshot from 2023-04-25 10-15-12](https://user-images.githubusercontent.com/24489294/234231761-5eb7217e-8639-4041-a6d6-2fc7934245f3.png)

**Comment by QuanyiLi** [comment]
Hmmm, I have no idea about your situation. It works great on my machine. Maybe it is due to your gym version? I use ```gym==0.25.2```

![Screenshot from 2023-04-25 13-48-01](https://user-images.githubusercontent.com/24489294/234281176-4f6a4252-13e6-47f4-926e-34839464b60b.png)
