### ISSUE TITLE
how to control vehicle  (render = Ture)

### ISSUE THREAD

**Issue by AHPUymhd** [metadriverse/metadrive#432]
May I ask how to control vehicle?    env.vehicle.set_velocity([1, 0.1], 10) can set vehicle's velocity directly  ,but how to set steer and acceleration ? I have searched metadrive.tests   but didn't find this function   please teach me ,thinking you very much !!!!!!!!

**Comment by QuanyiLi** [comment]
Just use ```env.step([Steering, throttle])``` to control the vehicle with acceleration and advance the simulation.

**Comment by AHPUymhd** [comment]
![图片](https://user-images.githubusercontent.com/72792297/234283620-5454aa09-86a8-41ef-8698-b6c64fb987e0.png)
![图片](https://user-images.githubusercontent.com/72792297/234283660-4a7c17ae-0298-46ec-a888-da66608d0e29.png)

**Comment by AHPUymhd** [comment]
but the vehicle  didn't move ,what's my problem?

**Comment by QuanyiLi** [comment]
in config set manual_control=False



发自我的 iPhone


------------------ Original ------------------
From: AHPUymhd ***@***.***&gt;
Date: Tue, Apr 25, 2023 1:58 PM
To: metadriverse/metadrive ***@***.***&gt;
Cc: Quanyi Li ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [metadriverse/metadrive] how to control vehicle  (render = Ture) (Issue #432)
