### ISSUE TITLE
out_of_route_done,on_continuous_line_done,crash_vehicle_done   didn't work

### ISSUE THREAD

**Issue by AHPUymhd** [metadriverse/metadrive#433]
why i set out_of_route_done,   on_continuous_line_done,   crash_vehicle_done   is true    ,but it didn't work   ,is the reason of   manual_control=True?

**Comment by AHPUymhd** [comment]
![图片](https://user-images.githubusercontent.com/72792297/235203374-987b3b1d-f33d-49d8-bb8b-d6fa01610d00.png)

**Comment by QuanyiLi** [comment]
Do you mean the ```done``` flag returned by ```env.step()```` is ```False```? I need more information, Could you provide the whole script?
