### ISSUE TITLE
I encounter a problem with vscode ,I can't run metadrive in vscode 

### ISSUE THREAD

**Issue by AHPUymhd** [metadriverse/metadrive#434]

**Comment by AHPUymhd** [comment]
![图片](https://user-images.githubusercontent.com/72792297/235280261-0e71fa91-bba6-4494-9138-718cc580d922.png)
![图片](https://user-images.githubusercontent.com/72792297/235280276-b1a686de-c34d-4bc3-9810-6ee874a02a18.png)
 the error is that

**Comment by QuanyiLi** [comment]
use ```pip install panda3d-simplepbr```
