### ISSUE TITLE
store_map for ScenarioEnv has some bugs

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#447]
![image](https://github.com/metadriverse/metadrive/assets/22206995/2e53ec5b-1899-4a32-80cb-7ca96d9d32db)

If we set store_map, the `new_map` will be the one in `self._stored_maps`.

However, the stored_maps might lost its `self.road_network` in destroy. So when `self.load_map(new_map)`, the map doesn't have `self.road_network` and this might lead to some problem. I am not sure if it will re-create `self.road_network` later.

And I am not sure whether this is a bug or not and how far it will affect other cases.

**Comment by QuanyiLi** [comment]
Could you give me a script for reproducing it? Why do you load the map again after destroying it?
