### ISSUE TITLE
[question] Can I use my own map

### ISSUE THREAD

**Issue by CarlDegio** [metadriverse/metadrive#449]
How does metadrive import the map drawn by myself?

I found it could import waymo or nuplan dataset, is this the only way?

**Comment by QuanyiLi** [comment]
Yes, now MetaDrive can load scenarios as long as it is the built-in format. So you can convert your map/scenario to that format to load customized scenarios and maps.

**Comment by QuanyiLi** [comment]
close as duplicated with #450
