### ISSUE TITLE
[Customized data loading] loading customized data and real-world data 

### ISSUE THREAD

**Issue by CarlDegio** [metadriverse/metadrive#450]
The `metadrive.examples.drive_in_argoverse` file in doc [dataset](https://metadrive-simulator.readthedocs.io/en/latest/read_data_from_dataset.html) has disappeared. 
Consider supplement it or switch to waymo/nusense/nuplan?

**Comment by QuanyiLi** [comment]
Yes, we deprecate the Argoverse Env now but provide support for nuScenes, nuPlan, and Level5 (coming) dataset now. 
You can check this repo: https://github.com/metadriverse/scenarionet

**Comment by QuanyiLi** [comment]
We are going to complete the doc of new MetaDrive and Scenarionet soon. But if your wanna have a try in advance, feel free to ask any questions!
