### ISSUE TITLE
[Bug] Top-down view needs flip y-axis

### ISSUE THREAD

**Issue by QuanyiLi** [metadriverse/metadrive#454]
As we unify the coordinate system now, the Pygame coordinate is left-hand, while the Panda coordinate is right-hand. ```pygame.transform.flip() needs to be called for flipping everything```

**Comment by QuanyiLi** [comment]
@pengzhenghao This issue is exactly what you have encountered recently. Calling `flip()` is a workaround but lower the efficiency. A good solution is to flip `y` axis by adding `-` to where the `position.y` is used in pygame API.

**Comment by pengzhenghao** [comment]
A even better solution is to have a unified `Position` class that inherently has three properties:

`p = Position(0.0, 0.0, 0.0)`
`p.panda3d_position`
`p.metadrive_position`
`p.pygame_position`
