### ISSUE TITLE
[Discussion] Unify top-down renderer and top-down obs

### ISSUE THREAD

**Issue by QuanyiLi** [metadriverse/metadrive#455]
@pengzhenghao I found we have two sets of top-down rendering functions which have a huge overlap in terms of functionality. Can we merge both into one? We can thus get unified APIs.

**Comment by QuanyiLi** [comment]
By the way, I wonder if pygame-renderer can run in the offscreen mode

**Comment by pengzhenghao** [comment]
> By the way, I wonder if pygame-renderer can run in the offscreen mode

sure of course!

> I found we have two sets of top-down rendering functions which have a huge overlap in terms of functionality. Can we merge both into one? We can thus get unified APIs.

Is it still an issue now?

**Comment by QuanyiLi** [comment]
The top-down-obs is still another set of API. But never mind. Let's just keep it as it is.
