### ISSUE TITLE
Get the lidar Observation and Image Observation at the same time

### ISSUE THREAD

**Issue by Sue0316** [metadriverse/metadrive#466]
Hi, I would like to ask is there any argument that I can adjust to get both of the image observation and lidar observation at the same time? Or is there any way to do so? Thank you so much! BTW. I'm using version 0.2.3

**Comment by QuanyiLi** [comment]
Actually, if the ```image_observation``` in your env config is set to ```True```, you are allowed to access the camera and lidar together by```env.vehicle.lidar.perceive(env.vehicle)``` and ```env.vehicle.image_sensor["rgb_camera"].get_pixels_array(env.vehicle, self.rgb_clip)```. If you wanna get the results of both sensors in the returned value of ```env.step()```, you can just write your own observation class by merging ```LidarStateObservation``` and ```ImageStateObservation```.

**Comment by Sue0316** [comment]
I see! Got it, Thank you so much for the answer. Really appreciate it.
