### ISSUE TITLE
rgb_camera observation shape

### ISSUE THREAD

**Issue by WeizhenWang-1210** [metadriverse/metadrive#473]
It seems like the observation is of shape ` {'image': (84, 84, 3, 3), 'state': (21,)}`. Why is there an extra dimension in image?

**Comment by QuanyiLi** [comment]
We stack the latest 3 images to inform temporal information. This parameter can be modified in env_config, I think. You can check the ```class ImageStateObservation``` to know more about it

**Comment by pengzhenghao** [comment]
It shouldn’t be a (3,3) at the end. If we stack 3 frames, we either grayscale the image and use channel=3, or we stack all channels to have 9 channels.Best,ZhenghaoOn Jul 19, 2023, at 12:31, Quanyi Li ***@***.***> wrote:﻿
We stack the latest 3 images to inform temporal information. This parameter can be modified in env_config, I think. You can check the class ImageStateObservation to know more about it

**Comment by QuanyiLi** [comment]
The default image observation is set to RGB now. I believe one can build the observation on their own. It doesn't matter.

**Comment by pengzhenghao** [comment]
Yes I know it’s customizable but a default one have shape (3,3) is a bug I guess (not sure how Weizheng has this)Best,ZhenghaoOn Jul 19, 2023, at 13:26, Quanyi Li ***@***.***> wrote:﻿
The default image observation is set to RGB now. I believe one can build the observation on their own. It doesn't matter.

**Comment by QuanyiLi** [comment]
Actually, I made this modification before...
