### ISSUE TITLE
video recording issue for bev

### ISSUE THREAD

**Issue by WeizhenWang-1210** [metadriverse/metadrive#474]
The cmd prompt `python -m metadrive.examples.generate_video_for_bev_and_interface` results in the following error:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\arnoe\OneDrive\桌面\main\metadrive\metadrive\examples\generate_video_for_bev_and_interface.py", line 100, in <module>
    img_bev = pygame.surfarray.array3d(img_bev)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arnoe\anaconda3\envs\bolei\Lib\site-packages\pygame\surfarray.py", line 190, in array3d
    width, height = surface.get_size()
                    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_size'`

In addition, the openCV package doesn't ship with OpenH264 Video Codec, and maybe it could be mentioned in the documentation.

**Comment by QuanyiLi** [comment]
I don't recommend to use the script, which may cause some issues sometimes. You can use the following code to capture top-down view image for every frame:
```
ret = env.render(mode="topdown", screen_size=(1600, 900), film_size=(6000, 6000), target_vehicle_heading_up=True)
pygame.image.save(ret, "top_down_{}_{}.png".format(env.current_seed, env.episode_step))
```
And then you can use ```ffmpeg``` to create video from the images.
