### ISSUE TITLE
Camera issue with XLVehicle

### ISSUE THREAD

**Issue by WeizhenWang-1210** [metadriverse/metadrive#475]
When the agent is XLVehicle, the RGB observation data is a bit off: specifically, the model will block the line of sight:
![80](https://github.com/metadriverse/metadrive/assets/82100464/2c73b3b9-7aa5-4648-9e8f-543499e160df)
I'm wondering how to adjust the camera position for he vehicle.

**Comment by QuanyiLi** [comment]
We don't expose related API. But you can do this by modifying the following code.

This line is for adjusting the position, related tothe  vehicle: https://github.com/metadriverse/metadrive/blob/cc8ca5f4736774b4424ed18a119f2c8b5cd53b6c/metadrive/component/vehicle_module/base_camera.py#L42

And this line is for adjusting the pose:
https://github.com/metadriverse/metadrive/blob/cc8ca5f4736774b4424ed18a119f2c8b5cd53b6c/metadrive/component/vehicle_module/rgb_camera.py#L23
