### ISSUE TITLE
Partial fix for "show_agent_name"

### ISSUE THREAD

**Issue by WeizhenWang-1210** [metadriverse/metadrive#476]
If target_vehicle_heading_up is set to "False", then replace line 503-507 in top_down_renderer.py  will correct the error:
`
img = self.pygame_font.render(
                        self.engine.object_to_agent(v.name),
                        True,
                        (0, 0, 0, 128),
                    )
`

In addition, one need to add `off = (position[0] - field[0] / 2, position[1] - field[1] / 2)` in the if block that evaluates target_vhicle_heading_up(line 448).

However, the texts are a bit off due to the rotation when target_vehicle_heading_up == True. I'm been struggling to fix that.

**Comment by pengzhenghao** [comment]
Could you make a PR for this?
