### ISSUE TITLE
Errors in running python -m metadrive.examples.train_generalization_experiment

### ISSUE THREAD

**Issue by Liuxueyi** [metadriverse/metadrive#477]
I fall into trouble with the following error.txt, what's the problem?Please.
Failure # 1 (occurred at 2023-07-26_16-42-25)
[36mray::PPO.train()[39m (pid=1477765, ip=10.1.20.90, repr=PPO)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 381, in train
    result = self.step()
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 792, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 2811, in _run_one_training_iteration
    results = self.training_step()
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 403, in training_step
    train_batch = synchronous_parallel_sample(
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(ValueError): [36mray::RolloutWorker.apply()[39m (pid=1478256, ip=10.1.20.90, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fd34b626b80>)
ValueError: The two structures don't have the same nested structure.

First structure: type=tuple str=(array([0.29166666, 0.29166666, 0.5       , 0.01234568, 0.5       ,
       0.5       , 0.5       , 0.        , 0.5       , 0.55      ,
       0.5       , 0.        , 0.5       , 0.5       , 0.95      ,
       0.5       , 0.        , 0.5       , 0.5       , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ], dtype=float32), {'overtake_vehicle_num': 0, 'velocity': 0.0, 'steering': 0.0, 'acceleration': 0.0, 'step_energy': 0.0, 'episode_energy': 0.0, 'policy': 'EnvInputPolicy', 'crash_vehicle': False, 'crash_object': False, 'crash_building': False, 'out_of_road': False, 'arrive_dest': False, 'max_step': False, 'env_seed': 5000, 'crash': False, 'step_reward': 0.0, 'cost': 0})

Second structure: type=ndarray str=[0.11674915 0.30998474 0.6659199  0.6621079  0.34599248 0.71242267
 0.30595112 0.9044908  0.05226379 0.59416175 0.8165471  0.17465371
 0.76822144 0.8787789  0.32980385 0.3680215  0.9607165  0.3338884
 0.03204363 0.17981572 0.2077567  0.3523252  0.2688484  0.33854407
 0.19367008 0.8827313  0.5335654  0.01957076 0.42577797 0.95378125
 0.5950324  0.8579008  0.8077767  0.98825175 0.8479597  0.28897753
 0.7143476  0.831593   0.99407727 0.141195   0.6668243  0.3558707
 0.7529741  0.7475806  0.22553313 0.5912977  0.70971006 0.8446364
 0.24104878 0.89292574 0.8972258  0.8796306  0.2801835  0.83028173
 0.03612844 0.19751254 0.24748509 0.11422067 0.24133429 0.39399981
 0.23521249 0.5849617  0.23427647 0.00804834 0.14166793 0.50088555
 0.8993754  0.2214399  0.38931155 0.15556931 0.62177247 0.41163203
 0.00372639 0.8861268  0.5021418  0.79261404 0.53415436 0.09496067
 0.85632616 0.01271426 0.9439562  0.4363169  0.8465177  0.887339
 0.04571987 0.89933324 0.61553776 0.06036156 0.18595743 0.15092865
 0.693601   0.59432507 0.42808986 0.8821047  0.28051636 0.36382285
 0.7648492  0.629676   0.8810711  0.87890625 0.9338025  0.3707494
 0.21632956 0.8612712  0.8419754  0.02680918 0.26118574 0.1741304
 0.60929596 0.85299283 0.6018974  0.11813898 0.40889326 0.32860497
 0.25941458 0.1407616  0.740489   0.71076995 0.83095294 0.93617857
 0.7025399  0.59570104 0.06488149 0.5948903  0.27253982 0.5266301
 0.88587517 0.11327457 0.5889977  0.74325544 0.9971115  0.9867098
 0.26450095 0.44148642 0.5891357  0.6134908  0.33457845 0.8279865
 0.18771328 0.7541053  0.41332677 0.840764   0.69236416 0.28998762
 0.9614413  0.626125   0.5750871  0.29708552 0.9716731  0.7104481
 0.2921893  0.3190845  0.23124321 0.8988485  0.3598052  0.06958736
 0.63654107 0.9172321  0.03605204 0.63732237 0.53700125 0.6362758
 0.35131803 0.382303   0.8356672  0.48392496 0.36376724 0.8317263
 0.5494364  0.9188885  0.4487756  0.00797319 0.4649505  0.47557053
 0.90698427 0.28936002 0.6483601  0.28136548 0.3046157  0.51947683
 0.18855321 0.00755246 0.6796611  0.33171883 0.76928025 0.4271612
 0.4755958  0.32644394 0.16719566 0.2836907  0.6644649  0.61201566
 0.69326264 0.80387    0.4905878  0.89263284 0.5301812  0.11198125
 0.5225794  0.07947049 0.84208554 0.34255716 0.8869685  0.9613837
 0.94724786 0.87414956 0.89213556 0.5159962  0.82956105 0.41124794
 0.7383505  0.14066601 0.652564   0.654649   0.11702713 0.5527537
 0.6553356  0.1857239  0.98417115 0.4983793  0.22188202 0.64044195
 0.08287298 0.14362794 0.5192818  0.05942718 0.09837595 0.7581581
 0.1934023  0.28895465 0.60773206 0.19799685 0.24030848 0.12552758
 0.18595582 0.5697647  0.5419944  0.79017794 0.5521683  0.7867081
 0.90193915 0.45550853 0.53418607 0.21601741 0.2835275  0.962417
 0.47294095 0.25573528 0.0855387  0.610372   0.92546654 0.69827795
 0.8496019  0.02710621 0.5986689  0.14369497 0.9284028  0.7336012
 0.4508437 ]

More specifically: Substructure "type=tuple str=(array([0.29166666, 0.29166666, 0.5       , 0.01234568, 0.5       ,
       0.5       , 0.5       , 0.        , 0.5       , 0.55      ,
       0.5       , 0.        , 0.5       , 0.5       , 0.95      ,
       0.5       , 0.        , 0.5       , 0.5       , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ], dtype=float32), {'overtake_vehicle_num': 0, 'velocity': 0.0, 'steering': 0.0, 'acceleration': 0.0, 'step_energy': 0.0, 'episode_energy': 0.0, 'policy': 'EnvInputPolicy', 'crash_vehicle': False, 'crash_object': False, 'crash_building': False, 'out_of_road': False, 'arrive_dest': False, 'max_step': False, 'env_seed': 5000, 'crash': False, 'step_reward': 0.0, 'cost': 0})" is a sequence, while substructure "type=ndarray str=[0.11674915 0.30998474 0.6659199  0.6621079  0.34599248 0.71242267
 0.30595112 0.9044908  0.05226379 0.59416175 0.8165471  0.17465371
 0.76822144 0.8787789  0.32980385 0.3680215  0.9607165  0.3338884
 0.03204363 0.17981572 0.2077567  0.3523252  0.2688484  0.33854407
 0.19367008 0.8827313  0.5335654  0.01957076 0.42577797 0.95378125
 0.5950324  0.8579008  0.8077767  0.98825175 0.8479597  0.28897753
 0.7143476  0.831593   0.99407727 0.141195   0.6668243  0.3558707
 0.7529741  0.7475806  0.22553313 0.5912977  0.70971006 0.8446364
 0.24104878 0.89292574 0.8972258  0.8796306  0.2801835  0.83028173
 0.03612844 0.19751254 0.24748509 0.11422067 0.24133429 0.39399981
 0.23521249 0.5849617  0.23427647 0.00804834 0.14166793 0.50088555
 0.8993754  0.2214399  0.38931155 0.15556931 0.62177247 0.41163203
 0.00372639 0.8861268  0.5021418  0.79261404 0.53415436 0.09496067
 0.85632616 0.01271426 0.9439562  0.4363169  0.8465177  0.887339
 0.04571987 0.89933324 0.61553776 0.06036156 0.18595743 0.15092865
 0.693601   0.59432507 0.42808986 0.8821047  0.28051636 0.36382285
 0.7648492  0.629676   0.8810711  0.87890625 0.9338025  0.3707494
 0.21632956 0.8612712  0.8419754  0.02680918 0.26118574 0.1741304
 0.60929596 0.85299283 0.6018974  0.11813898 0.40889326 0.32860497
 0.25941458 0.1407616  0.740489   0.71076995 0.83095294 0.93617857
 0.7025399  0.59570104 0.06488149 0.5948903  0.27253982 0.5266301
 0.88587517 0.11327457 0.5889977  0.74325544 0.9971115  0.9867098
 0.26450095 0.44148642 0.5891357  0.6134908  0.33457845 0.8279865
 0.18771328 0.7541053  0.41332677 0.840764   0.69236416 0.28998762
 0.9614413  0.626125   0.5750871  0.29708552 0.9716731  0.7104481
 0.2921893  0.3190845  0.23124321 0.8988485  0.3598052  0.06958736
 0.63654107 0.9172321  0.03605204 0.63732237 0.53700125 0.6362758
 0.35131803 0.382303   0.8356672  0.48392496 0.36376724 0.8317263
 0.5494364  0.9188885  0.4487756  0.00797319 0.4649505  0.47557053
 0.90698427 0.28936002 0.6483601  0.28136548 0.3046157  0.51947683
 0.18855321 0.00755246 0.6796611  0.33171883 0.76928025 0.4271612
 0.4755958  0.32644394 0.16719566 0.2836907  0.6644649  0.61201566
 0.69326264 0.80387    0.4905878  0.89263284 0.5301812  0.11198125
 0.5225794  0.07947049 0.84208554 0.34255716 0.8869685  0.9613837
 0.94724786 0.87414956 0.89213556 0.5159962  0.82956105 0.41124794
 0.7383505  0.14066601 0.652564   0.654649   0.11702713 0.5527537
 0.6553356  0.1857239  0.98417115 0.4983793  0.22188202 0.64044195
 0.08287298 0.14362794 0.5192818  0.05942718 0.09837595 0.7581581
 0.1934023  0.28895465 0.60773206 0.19799685 0.24030848 0.12552758
 0.18595582 0.5697647  0.5419944  0.79017794 0.5521683  0.7867081
 0.90193915 0.45550853 0.53418607 0.21601741 0.2835275  0.962417
 0.47294095 0.25573528 0.0855387  0.610372   0.92546654 0.69827795
 0.8496019  0.02710621 0.5986689  0.14369497 0.9284028  0.7336012
 0.4508437 ]" is not

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.apply()[39m (pid=1478256, ip=10.1.20.90, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fd34b626b80>)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 185, in apply
    raise e
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 616, in _process_observations
    processed = policy.agent_connectors(acd_list)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/connectors/agent/pipeline.py", line 41, in __call__
    ret = c(ret)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/connectors/connector.py", line 254, in __call__
    return [self.transform(d) for d in acd_list]
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/connectors/connector.py", line 254, in <listcomp>
    return [self.transform(d) for d in acd_list]
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/connectors/agent/obs_preproc.py", line 58, in transform
    d[SampleBatch.NEXT_OBS] = self._preprocessor.transform(
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/models/preprocessors.py", line 206, in transform
    self.check_shape(observation)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/models/preprocessors.py", line 69, in check_shape
    observation = convert_element_to_space_type(
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/ray/rllib/utils/spaces/space_utils.py", line 378, in convert_element_to_space_type
    return tree.map_structure(map_, element, sampled_element, check_types=False)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/tree/__init__.py", line 433, in map_structure
    assert_same_structure(structures[0], other, check_types=check_types)
  File "/home/oem/anaconda3/envs/meta/lib/python3.9/site-packages/tree/__init__.py", line 288, in assert_same_structure
    raise type(e)("%s\n"
ValueError: The two structures don't have the same nested structure.

First structure: type=tuple str=(array([0.29166666, 0.29166666, 0.5       , 0.01234568, 0.5       ,
       0.5       , 0.5       , 0.        , 0.5       , 0.55      ,
       0.5       , 0.        , 0.5       , 0.5       , 0.95      ,
       0.5       , 0.        , 0.5       , 0.5       , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ], dtype=float32), {'overtake_vehicle_num': 0, 'velocity': 0.0, 'steering': 0.0, 'acceleration': 0.0, 'step_energy': 0.0, 'episode_energy': 0.0, 'policy': 'EnvInputPolicy', 'crash_vehicle': False, 'crash_object': False, 'crash_building': False, 'out_of_road': False, 'arrive_dest': False, 'max_step': False, 'env_seed': 5000, 'crash': False, 'step_reward': 0.0, 'cost': 0})

Second structure: type=ndarray str=[0.11674915 0.30998474 0.6659199  0.6621079  0.34599248 0.71242267
 0.30595112 0.9044908  0.05226379 0.59416175 0.8165471  0.17465371

**Comment by QuanyiLi** [comment]
Hi,

I guess it is due to the upgrade from ```gym``` to ```gymnasium```.

Could you try ```from metadrive.env.gym_wrapper import GymEnvWrapper``` and do the following modification to the training config?

```
 env=GymEnvWrapper,
        env_config={
            "inner_class": MetaDriveEnv,
            "inner_config": dict(
            num_scenarios=tune.grid_search([1, 3, 5, 1000]),
            start_seed=tune.grid_search([5000]),
            random_traffic=False,
            traffic_density=tune.grid_search([0.1, 0.3])
        )
        }
```

**Comment by Liuxueyi** [comment]
Thanks for your reply! I have run the PPO experiments successfully using the Stable-Baselines3 with the newest MetaDrive version. I think there may be some problems with the version of rllib. By the way, when I use the env "MetaDrive-10env-v0" and set the config "use_render" to true, the map index is always 0,  is there any settings that cause this situation?

**Comment by QuanyiLi** [comment]
The number of maps in each environment is controlled by ```num_environments```, which is a field in env_config. Could you share your training config with me?

**Comment by Liuxueyi** [comment]
In addition, my training script is :
![image](https://github.com/metadriverse/metadrive/assets/65993745/a8f42dcc-97b5-4f58-b803-ac5439831bcc)

**Comment by QuanyiLi** [comment]
I replicate your error successfully. This is because you pass a new config dict ```{"use_render": True}```, which overwrites the original config where the ```num_scenarios``` is set to 1000. 

The overwrite of ```gym.make``` doesn't happen recursively, so you can ```{"use_render": True, "num_scenarios": 1000}``` instead.

**Comment by Liuxueyi** [comment]
It works! Thanks for your guidance！
