### ISSUE TITLE
How to extend the maps?

### ISSUE THREAD

**Issue by liuxubit** [metadriverse/metadrive#494]
Hello:
      I used the parking branch to simulate the parking situation. How can I make a bigger map by adding two or more maps together

**Comment by QuanyiLi** [comment]
Hi,

Thank you for your interest. In MetaDrive, the maps are actually composed by several basic blocks. Take the ParkingLot as an example. The map consists of a straight road (FirstBlock), parking spaces (ParkingLotBlock), and a three-way intersection (TIntersectionBlock). Thus for making a larger map, just add as many blocks as possible.

To be specific, modify this class to get a larger map by adding more blocks:

https://github.com/metadriverse/metadrive/blob/e2f1dc547a5cf03bf8e141ebbaab338a451ede49/metadrive/envs/marl_envs/marl_parking_lot.py#L145
