### ISSUE TITLE
Some questions about the state space and reward function of MetaDrive-based environments

### ISSUE THREAD

**Issue by c4cld** [metadriverse/metadrive#497]
In paper 'MetaDrive: Composing Diverse Driving Scenarios for Generalizable Reinforcement Learning' , the authors introduce the reward function as follows.

The reward function is composed of three parts as follows:
R = c_{1} * R_{disp} + c_{2} * R_{speed} + R_{term}
R_{disp}
The displacement reward R_{disp} = d_{t} - d_{t-1}, wherein the d_{t} and d_{t-1} denote the longitudinal movement of the target vehicle in Frenet coordinates of current lane between two consecutive time steps, provides dense reward to encourage agent to move forward.
R_{speed}
The speed reward R_{speed} = v_{t}/v_{max} incentivizes agent to drive fast. v_{t} and v_{max} denote the current
velocity and the maximum velocity (80 km/h), respectively.
R_{term}
A sparse terminal reward R_{term}, which is non-zero only at the last time step. At that step.  R_{term} is set to +10 if the vehicle reaches the destination, -5 for crashing others or violating traffic rules such as locating at undrivable area.
c_{1} is set to 1 and c_{2} is set to 0.1.

I have some questions about the state space and reward function of MetaDrive-based environments as follows:
1 What is the value range of R_{disp}?

**Comment by QuanyiLi** [comment]
It is generally between 0-2

**Comment by c4cld** [comment]
Thank you very much

**Comment by c4cld** [comment]
In R_{speed}, the agent is already motivated to drive as fast as possible. In this case, is it necessary to consider the completion time of the task in the reward function? 
In other words, in a fixed environment with a specific task, is motivating the agent to drive as fast as possible in the reward function equivalent to motivating the agent to finish the episode in the shortest possible time in the reward function?
