### ISSUE TITLE
How to use metaDrive with customized policies (vehicle path/speed planner)

### ISSUE THREAD

**Issue by GoroYeh-HRI** [metadriverse/metadrive#507]
Hi,
Thank you so much for the work. We really like your simulator and would like to use it with our own developed planner algorithms.
I wonder could you provide an example for using metaDrive with a customized planner?
After reading both paper and documentation, I still couldn't have a mind how to run your simulator with a customized path planner.

For example, if we have a path planner (not based on RL) and want to use that in your simulator, how should we use it?
Should we write our own environment file?

Also, does metaDrive supports ROS?
Thank you so much!

**Comment by QuanyiLi** [comment]
A basic loop for running the simulation with your planner is:
```
from metadrive.envs.metadrive_env import MetaDriveEnv

config=dict(use_render=True) # config
sim = MetaDriveEnv(config) 
observation, info = sim.reset() # initialize simulation

while True:
    action = your_planner(observation)
    observation, r, d, t, info = env.step(action)
```

In this way, you need to construct your observation class to make sure the returned  `observation` contains the information your planner needs. It then has to output `action=[steering, throttle]` for controlling the car. This way is inconvenient sometimes. Another way is to build a `BasePolicy` subclass:

```
from metadrive.envs.metadrive_env import MetaDriveEnv
from metadrive.policy.base_policy import BasePolicy

class YourPolicy(BasePolicy):
    ...

config=dict(use_render=True, agent_policy=YourPolicy) # config
sim = MetaDriveEnv(config) 
sim.reset() # initialize simulation

while True:
    # the action passed to environment won't take effect. Instead, `YourPolicy` will determine the movement
    env.step([0, 0]) 
```

A good example is https://github.com/metadriverse/metadrive/blob/72e842cd1d025bf676e4af8797a01e4aa282109f/metadrive/envs/safe_metadrive_env.py#L38

After running it, you will find the car is controlled by an IDM policy, which is implemented here: https://github.com/metadriverse/metadrive/blob/72e842cd1d025bf676e4af8797a01e4aa282109f/metadrive/policy/idm_policy.py#L177

For the ROS bridge, we are going to release it. @BoSmallEar Are we ready to provide the official ROS bridge? 

For the document, we are going to complete it before the end of this year. There are too many new features...
