### ISSUE TITLE
What does 91-dimensional observation space mean？

### ISSUE THREAD

**Issue by Morn1n** [metadriverse/metadrive#511]
Hi,I'm using Metadrive for multi-agent autonomous driving research.The default observation space dimension in the code is 91.I have already seen the documention.What does 91-dimensional observation space mean？My model training is slow.Can i change the observation space to speed up training?

**Comment by QuanyiLi** [comment]
@pengzhenghao Could you help with this?

**Comment by QuanyiLi** [comment]
I guess the class for collecting information is:

https://github.com/metadriverse/metadrive/blob/653431be036c818e38856f0148789aea13c4f5fc/metadrive/obs/state_obs.py#L162
