### ISSUE TITLE
docstring coverage message bot raises error when merge PR

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#520]
@QuanyiLi 
@BoSmallEar 

Do we have any idea to fix this..

**Comment by pengzhenghao** [comment]
It's working when the PR is not merged. It can find the PR webpage successfully so it can make comment on that PR. But when the PR is merged, it can't find the correct destination..

**Comment by pengzhenghao** [comment]
In repo main page:

<img width="735" alt="image" src="https://github.com/metadriverse/metadrive/assets/22206995/973e9514-0e9b-449d-a293-c6b77b327b83">

In PR:

<img width="468" alt="image" src="https://github.com/metadriverse/metadrive/assets/22206995/454104d3-7476-456c-8947-55f3ccd94dd2">

**Comment by QuanyiLi** [comment]
Can you specify when to trigger the bot? Only trigger it when we are committing things to PR.

**Comment by QuanyiLi** [comment]
Finished in #521. The action will bypass the docstring check now: https://github.com/metadriverse/metadrive/actions/runs/6587476374
