### ISSUE TITLE
Update numpy dependency to higher version?

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#540]
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
metadrive-simulator 0.4.1.2 requires numpy<=1.24.2,>=1.21.6, but you have numpy 1.26.0 which is incompatible.`

Does anything in updated numpy version break our code?

**Comment by QuanyiLi** [comment]
I don't know. It seems now we can loosen the version of numpy
