### ISSUE TITLE
unsuccessfully run train_generalization_experiment.py

### ISSUE THREAD

**Issue by man469** [metadriverse/metadrive#550]
When I run the train_generalization_experiment.py, the terminal returns following error:
cannot import name 'createGymWrapper' from 'metadrive.envs.gym_wrapper' (D:\Program Files\anaconda3\lib\site-packages\metadrive\envs\gym_wrapper.py)
but I checked the file there indeed a function named createGymWrapper in metadrive.envs.gym_wrapper. 
Does anyone know how to fix it? 
Thank you very much!!

**Comment by QuanyiLi** [comment]
That is strange. Could you provide the raw terminal output?
