### ISSUE TITLE
[Help Requst]Imcompatibale version with argoverse-api

### ISSUE THREAD

**Issue by l1xiao** [metadriverse/metadrive#553]
Hi,
I followed the "Read Data from Dataset" chapter as the doc described. And found that the argoverse-api requires numpy==1.19 but metadrive will install numpy=1.24.2. I set numpy==1.24.2 in argoverse-api setup.py, but still failed to run `python -m metadrive.examples.drive_in_argoverse`:
/usr/bin/python: No module named metadrive.examples.drive_in_argoverse

Is there any solution to this problem?

**Comment by QuanyiLi** [comment]
Sorry, Argoverse-related API and environment have been deprecated for quite a long time. However, [ScenarioNet](https://github.com/metadriverse/scenarionet) is going to support Argoverse soon! We expect to release Argoverse convertor before the end of this month.

**Comment by l1xiao** [comment]
Thanks for your reply!
