### ISSUE TITLE
Kinda wierd if want to change config of lidar

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#560]
```python
    vehicle_config=dict(
        lidar=dict(num_lasers=72, distance=40, num_others=0),
        ...
    ),
    sensors=dict(lidar=(Lidar, 40)),
```

Say we want to change the perceive distance of the Lidar in a MARL env. We need to set the above two configs at the same time.

**Comment by QuanyiLi** [comment]
I am going to fix this soon. After that, you only need to specify `num_lasers`
