### ISSUE TITLE
How to turn off the U-turn function of an autonomous vehicle at an intersection?

### ISSUE THREAD

**Issue by Morn1n** [metadriverse/metadrive#582]
Hi,I am using the metadrive simulation platform to conduct research on multi-agent reinforcement learning. The main research scenario is an intersection. I want to turn off the U-turn function of vehicles at the intersection and only keep straight and turn, what should I do?

**Comment by QuanyiLi** [comment]
You can set `enable_u_turn=False` to turn it off, just like what we did in https://github.com/metadriverse/metadrive/blob/126d6d068fa9f4a94db30aac0a5c62c2d85083d2/metadrive/envs/marl_envs/marl_intersection.py#L63
