### ISSUE TITLE
How to get the throttle/brake/steering value shown in the upper-right bar?

### ISSUE THREAD

**Issue by man469** [metadriverse/metadrive#586]
I am running the automode by drive_in_single_agent_env.py. I check the code that the action in the code seems always to be [0,0] because following code section:
line 62: o, r, tem, tc, info = env.step([0,0])
However, when I run the code, the action shown on the upper-right bar in the render is not always 0. So my question is how the agent get the action from auto mode and how to get the action value?

**Comment by QuanyiLi** [comment]
In this mode, the policy controlling ego car is specified by `agent_policy`. It is `ExpertPolicy` in that script and the bars show this policy's output. More information about the policy mechanism is at https://metadrive-simulator.readthedocs.io/en/latest/action.html.

The action value is stored in `env.vehicle.steering` and env.`vehicle.throttle_brake`.
