### ISSUE TITLE
ImportError: cannot import name '_load_shader_str' from 'simplepbr'

### ISSUE THREAD

**Issue by axelbr** [metadriverse/metadrive#591]
When installing metadrive and running the examples, I got the following error:
`ImportError: cannot import name '_load_shader_str' from 'simplepbr'`

It seems that the dependency `panda3d-simplepbr` does not have this member anymore. Downgrading to a version prior to 0.11 helped to fix this error.
I am using python 3.10

**Comment by QuanyiLi** [comment]
Hi,

Thanks for the feedback: ) 

Did you install it with `pip`? If it is installed from `git clone`, this should be addressed.

**Comment by axelbr** [comment]
I installed it with pip. But I guess it should be addressed anyways, since it's one of the recommended ways of installation.

**Comment by axelbr** [comment]
It works when I install it directly from Github.

**Comment by QuanyiLi** [comment]
Indeed, we should release a new PyPI package. Thank you for reminding us!
