### ISSUE TITLE
createGymWrapper is weridly named, and have we discussed it in documentation?

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#626]

**Comment by QuanyiLi** [comment]
It is in the environment section I believe. Also, you can have a reference for this function like `create_gym_wrapper=CreateGymWrapper` so it is compatible with existing code.

**Comment by pengzhenghao** [comment]
Yea I fixed thisBest,ZhenghaoOn Jan 31, 2024, at 06:45, Quanyi Li ***@***.***> wrote:﻿
It is in the environment section I believe. Also, you can have a reference for this function like create_gym_wrapper=CreateGymWrapper so it is compatible with existing code.

**Comment by QuanyiLi** [comment]
Solved. CLose
