### ISSUE TITLE
The posture of human in semantic map mismatches RGB images

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#645]
![semantic_25](https://github.com/metadriverse/metadrive/assets/22206995/b4e9b6d7-c734-4474-a999-f05304cacf83)

![rgb_19](https://github.com/metadriverse/metadrive/assets/22206995/e28bbd73-c30d-4a0d-b426-4da89d90f7ec)

**Comment by pengzhenghao** [comment]
this is a known issue in https://github.com/metadriverse/metadrive/pull/644

**Comment by pengzhenghao** [comment]
@QuanyiLi would you mind take a look on this issue? I can't find a solution in `Pedestrain` and `SementicCamera` classes

**Comment by QuanyiLi** [comment]
Just post the question on Panda3D forum
