### ISSUE TITLE
Why raw images has reversed channels?

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#651]
![image](https://github.com/metadriverse/metadrive/assets/22206995/27a4e4e6-490b-4316-8c72-bac5096e27f4)

You gotta set the channels to [2,1,0] so that you can see correct color if plotted with plt.imshow()

**Comment by QuanyiLi** [comment]
When using `cv2.imshow()`, we don't need to reverse right? So which library uses the right RGB order...
