### ISSUE TITLE
Error in the First Example in the Sensors Section of the Documentation

### ISSUE THREAD

**Issue by xiaobanni** [metadriverse/metadrive#717]
The first example in the Sensors section of the documentation (see link: https://metadrive-simulator.readthedocs.io/en/latest/sensors.html#sensors) results in an error. This seems to be a fundamental issue with BaseEnv, as running `base_env.py` directly also produces the error. Please address this issue.

**Comment by QuanyiLi** [comment]
Thank you for the feedback. This error is raised by the readthedoc server, and it works well on my local machine. We do need to figure out how to let the ReadTheDoc server do the offscreen rendering to avoid this...
