### ISSUE TITLE
Headless rendering: extracted image is colorless running in Docker container

### ISSUE THREAD

**Issue by bongbui321** [metadriverse/metadrive#721]
I'm currently running Metadrive in a Docker container and it seems that the image extracted from "rgb_camera" is all white (image below)
![image](https://github.com/metadriverse/metadrive/assets/47828508/02c8f78e-171a-436e-8d51-e922f7ed274a)

It runs fine on host machine (having colors and textures are correct). I have confirmed that textures and shaders are loaded (paths to assets are correct), but unsure why it is like the image above. I extracted the images from `rgb_camera.perceive()`

Are there veryfying steps that I can make to make sure that the textures and shaders are loaded correctly? 

Ah, I just narrowed down the issue to having no physical monitor or display port. The no-color display in the above image is from me initializing a virtual screen in xvfb first then run Metarive, but when I allow forwarding display from docker container to my host, every works fine. I wonder why?

Further narrowed it down to I think xvfb isn't utilizing Opengl to render. Not sure if ```OpenGL version string: 3.1 Mesa 21.2.6```
is compatible with Metadrive

**Comment by bongbui321** [comment]
My bad, this problem should have been solved, I was using Metadrive 4.2.3

**Comment by zhangqf2001** [comment]
I also encountered this problem, can I ask how you solved it?

**Comment by yuyangzhang323** [comment]
I have the same problem, how do you solve it?

**Comment by pengzhenghao** [comment]
Not sure if this issue still exists if you install metadrive via 
`pip install git+.....`

Feel free to reopen this issue.
