### ISSUE TITLE
 Unable to Find 'OLD' Folder - Need Assistance for PVP Model Evaluation in CARLA

### ISSUE THREAD

**Issue by Shivasairudrangi** [metadriverse/metadrive#724]
Hi,
https://github.com/metadriverse/pvp/blob/main/pvp/eval_script/carla/carla_eval_utils.py#L12

I hope this message finds you well. My name is Shivasai, and I am a final-year B.Tech student deeply impressed by your work on the PVP model.

I am currently working on implementing the PVP model but have encountered an issue. I cannot find the folder named 'OLD', which is preventing me from running any of the evaluation scripts in CARLA. As my project deadline is approaching soon, I would greatly appreciate your guidance and support in resolving this issue.

Thank you for your time and assistance.

Best regards,
Shivasai

**Comment by pengzhenghao** [comment]
Solved
