### ISSUE TITLE
Barriers/small dots on the map... what are they and how do I turn them off?

### ISSUE THREAD

**Issue by tiagorochag** [metadriverse/metadrive#726]
Hello all,

Does anyone know how to remove or change the parameter of those red dots that force vehicles to merge in the lane?

What map_config or other config parameter should we adjust in the env?

Thanks in advance, 

![meta_drive_dots](https://github.com/metadriverse/metadrive/assets/13020409/15b1f882-0ac4-4752-ad51-17dc5d0f185a)

**Comment by QuanyiLi** [comment]
These are traffic cones. Set `accident_prob=0` to turn off the generation for them

**Comment by tiagorochag** [comment]
Thanks for your answer !
