### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'remove_all_display_regions'

### ISSUE THREAD

**Issue by Asalif** [metadriverse/metadrive#732]
Hi all
Has anyone encountered this issues installing MetaDrive on macOS and found a solution?

**Comment by QuanyiLi** [comment]
Hi @Asalif 

MetaDrive can not run on MacOS now as Panda3D doesn't support it anymore due to the deprecation of OpenGL by Apple.

**Comment by maxime-desroches** [comment]
@Asalif To make metadrive works on ARM MacOS, you can use the changes from this commit : https://github.com/commaai/metadrive/pull/4/commits/7d7c7165822d9c97bb048d6b27d1f07fe0897d8c

ARM MacOS still supports OpenGL 4.1
