### ISSUE TITLE
MultiTask Meta-Learning

### ISSUE THREAD

**Issue by nil123532** [metadriverse/metadrive#766]
Hi, 
Thank you for this amazing project. 

I was wondering how can someone specify different  tasks in this environment, 

maybe different goal location or different driving behaviours

**Comment by nil123532** [comment]
Hi,
Grateful if someone could help me here!

**Comment by pengzhenghao** [comment]
We have implemented a multigoal environment in `metadrive/envs/multigoal_intersection.py`

Basically it's a single intersection. But we will provide detailed observations and rewards for all four cases: when the goal is move forward / turn left / right / U-turn.

Maybe this can be the meta learning env.
