### ISSUE TITLE
No module named 'metadrive.envs.real_data_envs.waymo_idm_env'

### ISSUE THREAD

**Issue by CC97** [metadriverse/metadrive#767]
Hi, when I try to use metadrive-scenario, there is an error missing moudel 'metadrive.envs.real_data_envs.waymo_idm_env'.

My environment is:
Ubuntu 20.04
Python 3.11
MetaDrive 0.4.2.3
Metadrive-scenario 0.0.1.0

$ python metadrive_scenario/examples/run_scenarios.py  --dataset env_num_3000_start_seed_0_synthetic --scenario_start=0 --scenario_end=3000 
Traceback (most recent call last):
  File "/home/advisor/Research/Cheng/metadrive-scenario/metadrive_scenario/examples/run_scenarios.py", line 1, in <module>
    from metadrive_scenario.utils.env_create_utils import create_env_and_config
  File "/home/advisor/Research/Cheng/metadrive-scenario/metadrive_scenario/utils/env_create_utils.py", line 3, in <module>
    from metadrive.envs.real_data_envs.waymo_idm_env import WaymoIDMEnv
ModuleNotFoundError: No module named 'metadrive.envs.real_data_envs.waymo_idm_env'

**Comment by pengzhenghao** [comment]
Seems like we already deprecated `metadrive_scenario` Are u still have problem with latest MetaDrive and ScenarioNet?
